pipeline:
  build:
    image: node:8.11.3-alpine
    commands:
      - npm install
      - npm test
  ssh-deploy:
    image: appleboy/drone-ssh
    pull: true  # always pull the latest version of the `drone-ssh` plugin         
    host: 
      - 10.140.0.2
    username: drone
    key_path: /root/.ssh/id_rsa
    script:
      - sudo mkdir /var/test4  # or whereever you put your `deploy.sh`   
    when:
      event: [push, tag, deployment]
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: drone-test
    template: > 
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}