pipeline:
  build:
    image: node:8.11.3-alpine
    commands:
      - npm install
      - npm start
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: drone-test
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}